version: '3.9'
services:
  amongus:
    container_name: amongus
    image: 'registry.richardxiong.com/amongus:latest'
    restart: unless-stopped
    environment:
      - DISCORD_TOKEN=$DISCORD_TOKEN
    labels:
      - traefik.enable=true
